[package]
name = "satdash-server"
version = "0.1.0"
edition = "2018"

[dependencies]
csv = "1.1.6"
reqwest = { version = "0.11.12", default-features = false, features = ["rustls-tls"] }
rocket = "0.5.0-rc.1"
serde = "1.0.145"
serde_json = "1.0.85"